In [6]:
import numpy as np

# возврат от 0 до 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights # вес
        self.bias = bias # смещение
    def forward(self, inputs): # прямое распространение
        total = np.dot(self.weights, inputs) + self.bias # сколярное произведение весов и входных данных
        return sigmoid(total)

class NN:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def forward(self, x):
        out_h1 = self.h1.forward(x)
        out_h2 = self.h2.forward(x)
        out_h3 = self.h3.forward(x)
        out_o1 = self.o1.forward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = NN()
x = np.array([1,5,4])
print(network.forward(x))

0.8160723773367224


In [9]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def forward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)

class NN:
    
    def __init__(self):
        weights = np.array([1, 0])
        bias = 1
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)
    
    def forward(self, x):
        out_h1 = self.h1.forward(x)
        out_h2 = self.h2.forward(x)
        out_o1 = self.o1.forward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.forward(np.array([out_h1, out_h2]))
        return np.array([out_o1, out_o2])
    
network = NN()
x = np.array([1, 5])
print(network.forward(x))

[0.86770265 0.86770265]


In [11]:
import numpy as np

def tanhF(x):
    return np.tanh(x)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def forward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return tanhF(total)

class NN:
    
    def __init__(self):
        weights = np.array([1, 0])
        bias = 1
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)
    
    def forward(self, x):
        out_h1 = self.h1.forward(x)
        out_h2 = self.h2.forward(x)
        out_o1 = self.o1.forward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.forward(np.array([out_h1, out_h2]))
        return np.array([out_o1, out_o2])
    
network = NN()
x = np.array([1, 5])
print(network.forward(x))

[0.96139597 0.96139597]


In [12]:
import numpy as np

def ReLU(x):
    return max(0.0,x)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def forward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return ReLU(total)

class NN:
    
    def __init__(self):
        weights = np.array([1, 0])
        bias = 1
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)
    
    def forward(self, x):
        out_h1 = self.h1.forward(x)
        out_h2 = self.h2.forward(x)
        out_o1 = self.o1.forward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.forward(np.array([out_h1, out_h2]))
        return np.array([out_o1, out_o2])
    
network = NN()
x = np.array([1, 5])
print(network.forward(x))

[3 3]


In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

url = r'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
d = pd.read_csv(url)

X = d.iloc[:, :-1].values
Y = d.iloc[:, -1].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.80, test_size = 0.20, stratify = Y, random_state = 123)

mlp_classifier = MLPClassifier(max_iter = 500).fit(X_train, Y_train)
pred = mlp_classifier.predict(X_test)

print("\nТест: %.3f"%mlp_classifier.score(X_test, Y_test))
print('Тренировка: %.3f'%mlp_classifier.score(X_train, Y_train))
print(f"\nМатрица путанницы:\n {confusion_matrix(Y_test, pred)}")
print(f"Потери : ", mlp_classifier.loss_)
print(f'Number of Coefs : ', len(mlp_classifier.coefs_))
print(f'Number of Intercepts : ', len(mlp_classifier.intercepts_))
print(f'Number of Iterations for Which Estimator Run : ', mlp_classifier.n_iter_)
print(f'Name of Output Layer Activation Function : ', mlp_classifier.out_activation_)


Тест: 0.933
Тренировка: 0.992

Матрица путанницы:
 [[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]
Потери :  0.054700414032811846
Number of Coefs :  2
Number of Intercepts :  2
Number of Iterations for Which Estimator Run :  500
Name of Output Layer Activation Function :  softmax


C:\Users\sinya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

url = r'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'
d = pd.read_csv(url)

X = d.iloc[:, :-1].values
Y = d.iloc[:, 1].values


X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=123)
mlp = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("R2 score: %.2f" % r2_score(y_test, y_pred))

print(mlp.n_layers_) 
print(mlp.hidden_layer_sizes) 
print(mlp.coefs_)

Mean squared error: 1438633681.82
R2 score: -0.33
4
(100, 50)
[array([[ 1.90820256e+00,  2.86903453e-25,  1.94722750e+00,
         1.71335979e+00,  1.97526501e+00,  1.75697029e+00,
         1.58984474e+00,  1.80399037e+00, -2.44473789e-26,
        -4.65990449e-10, -1.09567945e-01,  1.84812167e+00,
         1.63867741e+00,  1.94250116e+00,  1.92113082e+00,
         1.60873491e+00,  7.73936090e-14, -3.68619263e-24,
         1.78026880e+00,  1.74176863e-14, -8.86161281e-08,
         2.00962963e+00, -1.57282578e-24,  1.80452565e+00,
         1.56981945e+00,  1.67034472e+00,  1.85667765e+00,
         1.64289776e+00, -3.68518658e-02, -7.23936926e-03,
         1.54757934e+00,  1.95936427e+00,  1.85251202e+00,
         1.84947503e+00, -1.65432608e-15,  1.97653562e+00,
         1.78331852e+00,  6.05073753e-03,  1.74924118e+00,
         1.97322826e+00,  1.82199358e+00,  1.66241660e-25,
        -1.23521589e-20,  9.87891172e-25, -3.96855014e-08,
         1.98897665e+00,  1.97764617e+00, -1.4165347

C:\Users\sinya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
